cc_test(
  name = 'test_suite_aes.cbc',
  warning = 'no',
  srcs = [
    'test_suite_aes.cbc.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_aes.cfb',
  warning = 'no',
  srcs = [
    'test_suite_aes.cfb.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_aes.ecb',
  warning = 'no',
  srcs = [
    'test_suite_aes.ecb.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_aes.rest',
  warning = 'no',
  srcs = [
    'test_suite_aes.rest.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_arc4',
  warning = 'no',
  srcs = [
    'test_suite_arc4.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_base64',
  warning = 'no',
  srcs = [
    'test_suite_base64.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_blowfish',
  warning = 'no',
  srcs = [
    'test_suite_blowfish.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_camellia',
  warning = 'no',
  srcs = [
    'test_suite_camellia.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.aes',
  warning = 'no',
  srcs = [
    'test_suite_cipher.aes.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.arc4',
  warning = 'no',
  srcs = [
    'test_suite_cipher.arc4.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.blowfish',
  warning = 'no',
  srcs = [
    'test_suite_cipher.blowfish.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.camellia',
  warning = 'no',
  srcs = [
    'test_suite_cipher.camellia.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.des',
  warning = 'no',
  srcs = [
    'test_suite_cipher.des.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.gcm',
  warning = 'no',
  srcs = [
    'test_suite_cipher.gcm.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.null',
  warning = 'no',
  srcs = [
    'test_suite_cipher.null.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_cipher.padding',
  warning = 'no',
  srcs = [
    'test_suite_cipher.padding.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_ctr_drbg',
  warning = 'no',
  srcs = [
    'test_suite_ctr_drbg.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_debug',
  warning = 'no',
  srcs = [
    'test_suite_debug.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_des',
  warning = 'no',
  srcs = [
    'test_suite_des.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_dhm',
  warning = 'no',
  srcs = [
    'test_suite_dhm.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_ecdh',
  warning = 'no',
  srcs = [
    'test_suite_ecdh.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_ecdsa',
  warning = 'no',
  srcs = [
    'test_suite_ecdsa.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_ecp',
  warning = 'no',
  srcs = [
    'test_suite_ecp.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_error',
  warning = 'no',
  srcs = [
    'test_suite_error.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes128_de',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes128_de.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes128_en',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes128_en.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes192_de',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes192_de.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes192_en',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes192_en.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes256_de',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes256_de.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.aes256_en',
  warning = 'no',
  srcs = [
    'test_suite_gcm.aes256_en.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_gcm.camellia',
  warning = 'no',
  srcs = [
    'test_suite_gcm.camellia.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_hmac_drbg.misc',
  warning = 'no',
  srcs = [
    'test_suite_hmac_drbg.misc.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_hmac_drbg.nopr',
  warning = 'no',
  srcs = [
    'test_suite_hmac_drbg.nopr.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_hmac_drbg.no_reseed',
  warning = 'no',
  srcs = [
    'test_suite_hmac_drbg.no_reseed.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_hmac_drbg.pr',
  warning = 'no',
  srcs = [
    'test_suite_hmac_drbg.pr.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_hmac_shax',
  warning = 'no',
  srcs = [
    'test_suite_hmac_shax.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_md',
  warning = 'no',
  srcs = [
    'test_suite_md.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_mdx',
  warning = 'no',
  srcs = [
    'test_suite_mdx.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_mpi',
  warning = 'no',
  srcs = [
    'test_suite_mpi.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pbkdf2',
  warning = 'no',
  srcs = [
    'test_suite_pbkdf2.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pem',
  warning = 'no',
  srcs = [
    'test_suite_pem.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pk',
  warning = 'no',
  srcs = [
    'test_suite_pk.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pkcs1_v21',
  warning = 'no',
  srcs = [
    'test_suite_pkcs1_v21.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pkcs5',
  warning = 'no',
  srcs = [
    'test_suite_pkcs5.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pkparse',
  warning = 'no',
  srcs = [
    'test_suite_pkparse.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_pkwrite',
  warning = 'no',
  srcs = [
    'test_suite_pkwrite.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_rsa',
  warning = 'no',
  srcs = [
    'test_suite_rsa.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_shax',
  warning = 'no',
  srcs = [
    'test_suite_shax.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_version',
  warning = 'no',
  srcs = [
    'test_suite_version.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_x509parse',
  warning = 'no',
  srcs = [
    'test_suite_x509parse.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_x509write',
  warning = 'no',
  srcs = [
    'test_suite_x509write.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)

cc_test(
  name = 'test_suite_xtea',
  warning = 'no',
  srcs = [
    'test_suite_xtea.c',
  ],
  testdata = [
    'data_files',
    'suites',
  ],
  deps = '//essence/polarssl:polarssl'
)
